---
title: 清除异步的传染性
date: 2023-09-24 17:57:15
tags:
---

本文代码来源于：[清除异步的传染性](https://www.bilibili.com/video/BV1hp4y1A71j/?buvid=XX6505B6A5FE722C352C2CE14820CF8C308CB&is_story_h5=false&mid=CLy7chSW0K5I%2FKiNt1CySg%3D%3D&p=1&plat_id=116&share_from=ugc&share_medium=android&share_plat=android&share_session_id=1641ad7f-3dea-48f5-9b72-48c1ec69da5f&share_source=WEIXIN&share_tag=s_i&timestamp=1695447791&unique_k=1SzCR9x&up_id=666759136&vd_source=5a0ad7ce7857957d285555cd8472f9cb)  
侵删  

场景：  
如何将异步函数改为同步函数的形式，且尽量不改动函数，从而保证函数的纯度  
思路：  
使用同步函数来发网络请求，同时抛出一个错误(Promise对象)，在错误处理函数中等待网络请求返回，利用Promise的特性重新执行主函数。
扩展：  
react的`Suspense`组件就利用了这个方法
```javascript
    function getUser() {
        return fetch('./1.json')
    }

    function m1() {
        return getUser()
    }

    function main() {
        const user = m1()
        console.log(user)
    }

    function run(func) {
        let cache = {
            status: 'pending',
            value: null
        }
        const oldFetch = window.fetch
        window.fetch = function (...args) {
            if (cache.status === 'fulfilled') {
                return cache.value
            } else if (cache.status === 'rejected') {
                throw cache.value
            }
            const prom = oldFetch(...args).then(resp => {
                return resp.json()
            }).then((res) => {
                cache.status = 'fulfilled'
                cache.value = res
            }, err => {
                cache.status = 'rejected'
                cache.value = err
            })
            throw prom
        }

        // 执行入口函数
        try {
            func()
        } catch (err) {
            if (err instanceof Promise) {
                err.then(func, func).finally(() => {
                    window.fetch = oldFetch
                })
            }
        }

    }

    run(main)
```